### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by PotatoIsUs** [MadMax1960/Concursus#10]
I do not understand, i try to open the exe and nothing happens, ive downloaded 4 different versions of .net and nothing has changed, ive redownloaded the zip file twice, no change. all only thing that happens is that the little loading wheel appears for a second and then nothing? i dont understand

**Comment by MadMax1960** [comment]
Well Concursus specifically needs .net 6 which is found here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

If you're sure you've downloaded this, than maybe a computer restart might help in case somehow windows isn't registering it installed 6.0.
