### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by JonyPlayz12** [MadMax1960/Concursus#2]
When downloading it, it says it has a virus. Is it normal? 
![Screenshot 2023-10-18 172731](https://github.com/MadMax1960/Concursus/assets/148396222/1abb554b-637b-430c-938c-42e447869938)

**Comment by MadMax1960** [comment]
Same question as [here](https://github.com/MadMax1960/Concursus/issues/1), so same answer.

**Comment by JonyPlayz12** [comment]
> Same question as [here](https://github.com/MadMax1960/Concursus/issues/1), so same answer.

Oh alright, thanks

I guess it's safe lol
