### ISSUE TITLE
Simply does not work for me

### ISSUE THREAD

**Issue by 3pointreacalll** [MadMax1960/Concursus#8]
I cannot fathom why but the mods i download from gamebanana using the simple downlaod option (have not tried manual) simply do not load in the game and it says that they have loaded in the mod manager. i have tried using loads of diferent mods but  none work the mod manager has never said that anything has not worked however the models do not show up whatsoever so im a little dissapointed but mostly angry that it isnt working.
![image](https://github.com/MadMax1960/Concursus/assets/172941472/6896bf0d-37f2-4837-8c64-4a761d05a887)

**Comment by MadMax1960** [comment]
The log there shows the mod manager working properly, have you installed the needed mods for models to load? Alongside Bepinex?

**Comment by 3pointreacalll** [comment]
I dont know what Bepinex is P.S. i am pretty knew to modding
